trigger:
  branches:
    include:
      - infra/dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: terraform-credentials

steps:
  - task: Checkout@1
    displayName: 'Checkout código'
  
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: '1.5.5'
    displayName: 'Instalar Terraform'

  - script: |
      terraform init -reconfigure \
        -backend-config="resource_group_name=rg-terraform-state" \
        -backend-config="storage_account_name=terraformstate2644016" \
        -backend-config="container_name=tfstate" \
        -backend-config="key=terraform.tfstate"
    workingDirectory: infra
    displayName: 'Inicializar Terraform'

  - script: |
      terraform apply -auto-approve
    workingDirectory: infra
    displayName: 'Aplicar cambios con Terraform'
