trigger:
  branches:
    include:
      - infra/dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: dockerhub-credentials
  - name: environment
    value: dev
  - name: tf_version
    value: '1.5.5'

steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '$(tf_version)'
    displayName: 'Instalar Terraform'

  - script: terraform --version
    displayName: 'Verificar versión de Terraform'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Kevin'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        cd infra
        
        echo "Inicializando Terraform..."
        terraform init -reconfigure

        echo "Haciendo plan de Terraform..."
        terraform plan -var-file="terraform.tfvars" -out=tfplan

        echo "Aplicando Terraform plan..."
        terraform apply -auto-approve tfplan
    displayName: 'Inicializar y desplegar infraestructura DEV'