trigger:
  branches:
    include:
      - infra/prod

pool:
  vmImage: 'ubuntu-latest'

variables:
  environment: production
  tf_version: '1.5.5'

steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '$(tf_version)'
    displayName: 'Instalar Terraform'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
    displayName: 'Usar Python para Azure CLI'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Kevin'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        cd infra
        rm -rf .terraform terraform.tfstate tfplan
        terraform init -reconfigure \
          -backend-config="resource_group_name=rg-terraform-state" \
          -backend-config="storage_account_name=terraformstate2644016" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=prod.terraform.tfstate"
        terraform plan -var-file="terraform.prod.tfvars" -out=tfplan
        terraform apply -auto-approve tfplan
    displayName: 'Desplegar infraestructura PRODUCTION con Terraform'
