trigger:
  paths:
    include:
      - 'infra/dev'

variables:
  - name: ARM_CLIENT_ID
    value: $(ARM_CLIENT_ID)
  - name: ARM_CLIENT_SECRET
    value: $(ARM_CLIENT_SECRET)
  - name: ARM_SUBSCRIPTION_ID
    value: $(ARM_SUBSCRIPTION_ID)
  - name: ARM_TENANT_ID
    value: $(ARM_TENANT_ID)

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: deploy
  displayName: 'Deploy Infrastructure'
  steps:
  - checkout: self

  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
    displayName: 'Setup Terraform'
    inputs:
      terraformVersion: 'latest'

  - task: TerraformCLI@0
    displayName: 'Terraform Init'
    inputs:
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
      backendType: 'selfConfigured'

  - task: TerraformCLI@0
    displayName: 'Terraform Apply'
    inputs:
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
      commandOptions: '-auto-approve'