trigger:
  branches:
    include:
      - infra/dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: dockerhub-credentials
  - name: environment
    value: dev
  - name: tf_version
    value: '1.5.5'

steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '$(tf_version)'
    displayName: 'Instalar Terraform'

  - script: terraform --version
    displayName: 'Verificar versión de Terraform'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Kevin'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        cd infra
        
        echo "Inicializando Terraform backend..."
        terraform init -reconfigure \
          -backend-config="resource_group_name=rg-terraform-state" \
          -backend-config="storage_account_name=terraformstate2644016" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=terraform.tfstate"

        echo "Haciendo Terraform plan..."
        terraform plan -var-file="terraform.tfvars" -out=tfplan

        echo "Aplicando Terraform plan..."
        terraform apply -auto-approve tfplan
    displayName: 'Inicializar, planificar y aplicar infraestructura DEV'
