trigger:
  branches:
    include:
      - infra/prod

pool:
  vmImage: 'ubuntu-latest'

variables:
  environment: production
  tf_version: '1.5.5'

steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '$(tf_version)'
    displayName: 'Instalar Terraform'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
    displayName: 'Usar Python para Azure CLI'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Kevin'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        cd infra
        terraform init

        if az group show --name rg-prod-microservices &> /dev/null; then
          echo "Importando Resource Group existente..."
          terraform import azurerm_resource_group.rg /subscriptions/$(az account show --query id -o tsv)/resourceGroups/rg-prod-microservices || true
        else
          echo "No existe el Resource Group. Terraform lo creará."
        fi
    displayName: 'Verificar e importar recursos si existen'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Kevin'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        cd infra
        terraform plan -var-file="terraform.prod.tfvars" -out=tfplan
        terraform apply -auto-approve tfplan
    displayName: 'Desplegar infraestructura PRODUCTION con Terraform'
