trigger:
  paths:
    include:
      - infra/dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  ARM_CLIENT_ID: $(ARM_CLIENT_ID)
  ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
  ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
  ARM_TENANT_ID: $(ARM_TENANT_ID)

steps:
  - task: Checkout@1
    displayName: 'Checkout code'

  - task: UseTerraform@0
    displayName: 'Setup Terraform'
    inputs:
      terraformVersion: 'latest'

  - script: |
      terraform init
    displayName: 'Terraform Init'
    workingDirectory: infra

  - script: |
      terraform apply -auto-approve
    displayName: 'Terraform Apply'
    workingDirectory: infra