trigger:
  branches:
    include:
      - main  # o tu branch correcto

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: terraform-credentials

steps:
  - task: Checkout@1
    displayName: 'Checkout código'

  - task: TerraformInstaller@1
    displayName: 'Instalar Terraform'
    inputs:
      terraformVersion: '1.5.5'

  - script: |
      echo "Exportando variables de autenticación..."
      export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
      export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
      export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
      export ARM_TENANT_ID=$(ARM_TENANT_ID)

      echo "Inicializando Terraform..."
      terraform init -reconfigure \
        -backend-config="resource_group_name=rg-terraform-state" \
        -backend-config="storage_account_name=terraformstate2644016" \
        -backend-config="container_name=tfstate" \
        -backend-config="key=terraform.tfstate"

      echo "Aplicando infraestructura..."
      terraform apply -auto-approve
    workingDirectory: infra
    displayName: 'Inicializar y aplicar Terraform'
