trigger:
  branches:
    include:
      - infra/dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  environment: dev
  tf_version: '1.5.5'

steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '$(tf_version)'
    displayName: 'Instalar Terraform'

  - script: terraform --version
    displayName: 'Verificar versión de Terraform'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
    displayName: 'Usar Python para Azure CLI'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Kevin'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        cd infra

        terraform init -reconfigure \
          -backend-config="resource_group_name=rg-terraform-state" \
          -backend-config="storage_account_name=terraformstate2644016" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=dev.terraform.tfstate"
    displayName: 'Terraform Init'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Kevin'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        cd infra

        terraform plan -var-file="terraform-dev.tfvars" -out=tfplan
    displayName: 'Terraform Plan'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Kevin'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        cd infra

        terraform apply -auto-approve tfplan
    displayName: 'Terraform Apply'
