trigger:
  branches:
    include:
      - infra/prod

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: terraform-credentials
  - name: environment
    value: production
  - name: tf_version
    value: '1.5.5'

steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '$(tf_version)'
    displayName: 'Instalar Terraform'

  - script: terraform --version
    displayName: 'Verificar versión de Terraform'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
    displayName: 'Usar Python para Azure CLI'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Kevin'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
        export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
        export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
        export ARM_TENANT_ID=$(ARM_TENANT_ID)

        cd infra

        terraform init -reconfigure \
          -backend-config="resource_group_name=rg-terraform-state-prod" \
          -backend-config="storage_account_name=terraformstate264402" \
          -backend-config="container_name=tfstate-prod" \
          -backend-config="key=terraform.tfstate.prod"
    displayName: 'Terraform Init'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Kevin'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
        export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
        export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
        export ARM_TENANT_ID=$(ARM_TENANT_ID)

        cd infra

        terraform plan -var-file="terraform.prod.tfvars" -out=tfplan
    displayName: 'Terraform Plan'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Kevin'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
        export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
        export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
        export ARM_TENANT_ID=$(ARM_TENANT_ID)

        cd infra

        terraform apply -auto-approve tfplan
    displayName: 'Terraform Apply'