trigger: none

resources:
  pipelines:
    - pipeline: infraPipeline
      source: SanjoDB.microservice-app-example-DEV
      trigger:
        branches:
          include:
            - infra/dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'VM-DEV-CONNECTION'
    runOptions: 'inline'
    inline: |
      echo "Instalando herramientas en la VM dev"
      export DEBIAN_FRONTEND=noninteractive
      sudo apt-get update -y

      # Java para users-api
      sudo apt-get install -y openjdk-17-jdk

      # NodeJS 16.x y npm actualizado
      curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      sudo apt-get install -y nodejs
      sudo npm install -g npm@latest

      # Go para auth-api
      sudo apt-get install -y golang

      # Python para log-processor
      sudo apt-get install -y python3 python3-pip

      # pm2 para ejecutar apps en segundo plano
      sudo npm install -g pm2

      # Clonar repositorio si no existe
      cd /home/azureuser
      if [ ! -d "microservice-app-example" ]; then
        git clone https://github.com/SanjoDB/microservice-app-example.git
      fi

      #Configurar pm2 para arranque automático
      pm2 startup systemd -u azureuser --hp /home/azureuser
  displayName: 'Instalar stack base en la VM'
