trigger:
  branches:
    include:
      - feature/*
  paths:
    include:
      - users-api/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  vm_path: '/home/azureuser/microservice-app-example'
  service_name: 'users-api'
  jar_name: 'users-api-0.0.1-SNAPSHOT.jar'

steps:
- task: SSH@0
  name: InstalarStackBase
  inputs:
    sshEndpoint: VM-DEV-CONNECTION
    runOptions: inline
    inline: |
      echo "Instalando herramientas base en la VM de desarrollo"
      export DEBIAN_FRONTEND=noninteractive
      sudo apt-get update -y
      sudo apt-get install -y \
        openjdk-17-jdk \
        python3 python3-pip \
        golang \
        build-essential \
        redis-server \
        curl git ca-certificates apt-transport-https gnupg lsb-release
      
      # Node.js 16 (compatible con todos los servicios en Node y frontend)
      curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      sudo apt-get install -y nodejs
      sudo npm install -g npm@latest pm2

      # Instalar paquetes de Python requeridos por log-processor
      sudo pip3 install redis==2.10.6 py_zipkin requests cython

      # Crear carpeta de trabajo
      cd ~
      if [ ! -d "microservice-app-example" ]; then
        git clone https://github.com/SanjoDB/microservice-app-example.git
      else
        echo "Repositorio ya clonado."
      fi

      echo "Entorno listo para todos los microservicios"
  displayName: "Instalar stack base en la VM"

