trigger:
  branches:
    include:
      - feature/*
  paths:
    include:
      - users-api/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  vm_path: '/home/azureuser/microservice-app-example'
  service_name: 'users-api'
  jar_name: 'users-api-0.0.1-SNAPSHOT.jar'

steps:
- task: SSH@0
  name: InstalarStack
  inputs:
    sshEndpoint: VM-DEV-CONNECTION
    runOptions: inline
    inline: |
      echo "🔧 Instalando herramientas en la VM dev"
      export DEBIAN_FRONTEND=noninteractive
      sudo apt-get update -y

      # Java para users-api
      sudo apt-get install -y openjdk-17-jdk

      # Node.js 16 y npm moderno
      curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      sudo apt-get install -y nodejs
      sudo npm install -g npm@latest

      # Go para auth-api
      sudo apt-get install -y golang

      # Python para log-processor
      sudo apt-get install -y python3 python3-pip

      # pm2 para ejecución de procesos NodeJS
      sudo npm install -g pm2

      # Clonar el repo si no existe
      cd ~
      if [ ! -d "microservice-app-example" ]; then
        git clone https://github.com/SanjoDB/microservice-app-example.git
      else
        echo "Repositorio ya existe. Saltando clonación."
      fi
      echo "✅ Stack base instalado correctamente"
  displayName: "Instalar stack base en la VM"
