- name: Instalar git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Instalar Docker Compose
  shell: |
    curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
  args:
    creates: /usr/local/bin/docker-compose

- name: Levantar contenedores con Docker Compose
  shell: docker-compose up -d
  args:
    chdir: /home/azureuser/microservice-app-example
