- name: Ejecutar docker-compose
  apt:
    name: docker-compose
    state: present
    update_cache: yes

- name: Verificar variables dockerhub_username
  debug:
    msg: "Username: {{ dockerhub_username }}

- name: Docker login a DockerHub
  shell: |
    echo '{{ dockerhub_password }}' | docker login --username '{{ dockerhub_username }}' --password-stdin


- name: Levantar contenedores con Docker Compose
  shell: docker compose up -d
  args:
    chdir: /home/azureuser/microservice-app-example

