- name: Ejecutar docker-compose
  apt:
    name: docker-compose
    state: present
    update_cache: yes

- name: Docker login a DockerHub
  docker_login:
    registry_url: https://index.docker.io/v1/
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_password }}"

- name: Levantar contenedores con Docker Compose
  shell: docker compose up -d
  args:
    chdir: /home/azureuser/microservice-app-example
