- name: Ejecutar docker-compose
  apt:
    name: docker-compose
    state: present
    update_cache: yes

- name: Verificar variables dockerhub_username
  debug:
    msg: "Username: {{ dockerhub_username }}"

- name: Crear carpeta ~/.docker y desactivar credStore
  shell: |
    mkdir -p ~/.docker
    echo '{"credsStore":""}' > ~/.docker/config.json

- name: Docker login a DockerHub
  shell: |
    echo '{{ dockerhub_password }}' | docker --config ~/.docker login --username '{{ dockerhub_username }}' --password-stdin

- name: Levantar contenedores con Docker Compose
  shell: docker compose up -d
  args:
    chdir: /home/azureuser/microservice-app-example
