trigger:
  branches:
    include:
      - feature/*
      - main
  paths:
    include:
      - frontend/**

pool:
  vmImage: ubuntu-latest

variables:
  service_dir: 'frontend'
  vm_ip: '172.172.172.182'
  remote_dir: '~/microservice-app-example/frontend'

stages:
- stage: BuildAndDeploy
  jobs:
  - job: DeployFrontend
    displayName: 'Deploy Frontend'
    steps:
      - checkout: self

      - task: NodeTool@0
        inputs:
          versionSpec: '14.x'
        displayName: 'Instalar Node.js 14'

      - script: |
          sudo apt update
          sudo apt install -y python2
          sudo ln -sf /usr/bin/python2 /usr/bin/python
        displayName: 'Instalar Python 2'

      - script: |
          cd frontend
          npm ci
          npm run build
        displayName: 'Instalar dependencias y construir frontend'

      - task: CopyFilesOverSSH@0
        inputs:
          sshEndpoint: VM-DEV-CONNECTION
          sourceFolder: $(Build.SourcesDirectory)/frontend
          contents: '**'
          targetFolder: $(remote_dir)
        displayName: 'Copiar archivos a la VM'

      - task: SSH@0
        inputs:
          sshEndpoint: VM-DEV-CONNECTION
          runOptions: inline
          inline: |
            echo "Desplegando frontend en la VM"
            pm2 delete frontend || true
            cd $(remote_dir)
            PORT=8080 AUTH_API_ADDRESS=http://127.0.0.1:8000 TODOS_API_ADDRESS=http://127.0.0.1:8082 pm2 start "npm start" --name frontend
        displayName: 'Ejecutar en la VM'