trigger:
  branches:
    include:
      - feature/*
      - main
  paths:
    include:
      - users-api/**

pool:
  vmImage: ubuntu-latest

variables:
  service_dir: 'users-api'
  artifact_name: 'users-api-0.0.1-SNAPSHOT.jar'
  vm_ip: '172.172.172.182'
  remote_dir: '~/microservice-app-example/users-api'

stages:
- stage: BuildAndDeploy
  jobs:
  - job: Build
    displayName: Build users-api
    steps:
    - checkout: self

    - script: |
        cd $(service_dir)
        chmod +x mvnw
        ./mvnw clean install
      displayName: Build with Maven

    - publish: $(service_dir)/target/$(artifact_name)
      artifact: users-jar

  - job: Deploy
    displayName: Deploy to dev VM
    dependsOn: Build
    steps:
    - download: current
      artifact: users-jar

    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: VM-DEV-CONNECTION
        sourceFolder: $(Pipeline.Workspace)/users-jar
        contents: $(artifact_name)
        targetFolder: $(remote_dir)/target
      displayName: Copiar JAR a la VM

    - task: SSH@0
      inputs:
        sshEndpoint: VM-DEV-CONNECTION
        runOptions: inline
        inline: |
          echo "⚙️ Desplegando users-api en la VM"
          pm2 delete users-api || true
          cd $(remote_dir)
          JWT_SECRET=PRFT SERVER_PORT=8083 pm2 start "java -jar target/$(artifact_name)" --name users-api
      displayName: Ejecutar en la VM
