trigger:
  branches:
    include:
      - feature/*
      - main
  paths:
    include:
      - users-api/**

pool:
  vmImage: ubuntu-latest

variables:
  service_dir: 'users-api'
  artifact_name: 'users-api-0.0.1-SNAPSHOT.jar'
  vm_ip: '172.172.172.182'
  remote_dir: '~/microservice-app-example/users-api'

stages:
- stage: Build
  displayName: 'Validar compilación local en Azure DevOps'
  jobs:
    - job: BuildOnly
      displayName: 'Compilar users-api localmente (sin desplegar)'
      steps:
        - checkout: self

        - task: JavaToolInstaller@0
          inputs:
            versionSpec: '8'
            jdkArchitectureOption: 'x64'
            jdkSourceOption: 'PreInstalled'
          displayName: 'Asegurar JDK 8'

        - script: |
            cd $(service_dir)
            chmod +x mvnw
            export JWT_SECRET=PRFT
            export SERVER_PORT=8083
            ./mvnw clean install -DskipTests
          displayName: 'Compilar users-api (verificación)'

- stage: DeployToVM
  displayName: 'Deploy en VM de Desarrollo desde Git'
  dependsOn: Build
  condition: succeeded()
  jobs:
    - job: DeployUsersApi
      displayName: 'Desplegar users-api directamente desde el repo en la VM'
      steps:
        - checkout: none

        - task: SSH@0
          inputs:
            sshEndpoint: VM-DEV-CONNECTION
            runOptions: inline
            inline: |
              echo "Git Pull en la VM"
              cd ~/microservice-app-example
              git pull origin main

              echo "Entrando a $(remote_dir)"
              cd $(remote_dir)

              echo "Cerrando instancia anterior de users-api"
              pm2 delete users-api >/dev/null 2>&1 || echo "No había instancia corriendo"

              echo "Compilando dentro de la VM"
              export JWT_SECRET=PRFT
              export SERVER_PORT=8083
              chmod +x mvnw
              ./mvnw clean install -DskipTests

              echo "Iniciando users-api en PM2"
              pm2 start "java -jar target/$(artifact_name)" --name users-api
          displayName: 'Compilar y ejecutar dentro de la VM'
