trigger:
  branches:
    include:
      - feature/*
      - master
  paths:
    include:
      - users-api/**

pool:
  vmImage: ubuntu-latest

variables:
  service_dir: 'users-api'
  vm_ip: '172.172.175.246'
  remote_base_dir: '~/microservice-app-example'
  remote_service_dir: '~/microservice-app-example/users-api'

stages:
- stage: BuildAndDeploy
  jobs:
  - job: BuildAuthApi
    displayName: 'Build y Deploy de Auth API'
    steps:
      - checkout: self

      - task: CopyFilesOverSSH@0
        inputs:
          sshEndpoint: VM-DEV-CONNECTION
          sourceFolder: $(service_dir)
          contents: '**'
          targetFolder: $(remote_service_dir)
        displayName: 'Copiar carpeta actualizada a la VM'

      - task: SSH@0
        inputs:
          sshEndpoint: VM-DEV-CONNECTION
          runOptions: inline
          inline: |
            echo "Reconstruyendo y levantando users-api vía Docker Compose"
            cd $(remote_base_dir)
            
            # Redirigir la salida de docker-compose a un archivo para evitar que Azure lo marque como error
            docker-compose build users-api > build_output.log 2>&1
            BUILD_STATUS=$?

            if [ $BUILD_STATUS -ne 0 ]; then
              cat build_output.log
              echo "##vso[task.logissue type=error]Error en la construcción del users-api."
              exit 1
            else
              # Mostrar el resultado de la construcción como mensaje informativo
              echo "##vso[task.logissue type=warning]Build de users-api completado exitosamente."
            fi

            echo "Levantando contenedor users-api..."
            # Forzar recreación del contenedor con --force-recreate y redireccionar salida
            docker-compose up -d --force-recreate users-api > deploy_output.log 2>&1
            DEPLOY_STATUS=$?
            
            if [ $DEPLOY_STATUS -ne 0 ]; then
              cat deploy_output.log
              echo "##vso[task.logissue type=error]Error al desplegar users-api."
              exit 1
            fi
            
            # Verificar que el contenedor esté ejecutándose
            CONTAINER_STATUS=$(docker-compose ps -q users-api | xargs docker inspect -f '{{.State.Running}}' 2>/dev/null)
            if [ "$CONTAINER_STATUS" != "true" ]; then
              echo "##vso[task.logissue type=error]El contenedor users-api no está en ejecución."
              exit 1
            else
              echo "##vso[task.logissue type=warning]Contenedor users-api desplegado correctamente."
            fi
        displayName: 'Reconstruir y levantar contenedor users-api'