- name: Instalar dependencias de Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: yes

- name: Agregar la clave GPG oficial de Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Agregar el repositorio oficial de Docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Actualizar cache de paquetes
  apt:
    update_cache: yes

- name: Instalar Docker Engine (CE), CLI y containerd
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Habilitar Docker para iniciar al arranque
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Agregar usuario azureuser al grupo docker
  user:
    name: azureuser
    groups: docker
    append: yes
